version: "3.8"
services:
  pymetrics:
    build: ./
    container_name: pymetrics
    env_file: ./cloud/.env
    volumes:
      # Bind Mount
      - ./logs:/pymetrics/logs
      # Anonymous Volume
      - /pymetrics/logs/sys_info
      # Named Volume
      - logs:/pymetrics/logs

volumes:
   logs:
